### ISSUE TITLE
The struture of generator of ImageNet benchmark

### ISSUE THREAD

**Issue by MasterLX** [GT-RIPL/AlwaysBeDreaming-DFCIL#5]
Nice work! But i have some little question.
(1)Could you provide the structure details of generators on ImageNet and TinyImageNet benchmarks? i.e., F_\phi in Eq(7).
(2)Could you publish the code of ImageNet and TinyImageNet benchmarks?

**Comment by jamessealesmith** [comment]
@MasterLX I have cleaned this code up and am currently verifying it. As soon as verification is complete, I will push it.
