### ISSUE TITLE
Resnet backbone in ImageNet experiments

### ISSUE THREAD

**Issue by ibadiu** [GT-RIPL/AlwaysBeDreaming-DFCIL#7]
Dear James,
Thanks for sharing the code of your method!
A quick question regarding the ResNet architecture used in
experiments/imnet-fivetask.sh 
and 
experiments/tinyimnet-twentytask.sh
You have "MODELNAME=resnet32" in both scripts.
Shouldn't this be resnet18 as stated in the paper?
Thanks!

**Comment by jamessealesmith** [comment]
Thank you, I have pushed the change. As mentioned in the paper, ImageNet is a weakness of our method and only recorded for transparency. In order to achieve better results, either more compute or an updated model inversion technique would be required.
